# Generated by Django 5.0.6 on 2024-07-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diseño', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseñador', models.CharField(max_length=100)),
                ('diseño', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='diseños/')),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
